GPU: [0]

VERBOSE: True

# ---------------------------------------------------
# OPTIMIZATION
# ---------------------------------------------------
OPTIM:
  BATCH_SIZE: 8          # Good balance for GPU memory
  NUM_EPOCHS: 300        # Standard for deraining
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  BETA1: 0.9

# ---------------------------------------------------
# TRAINING
# ---------------------------------------------------
TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False

  TRAIN_PS: 256          # Patch size for training
  VAL_PS: null           # Full-resolution validation

  # ✅ IMPORTANT → Dataset ROOT (not train_set)
  TRAIN_DIR: /content/MFDNet-main/GT-RAIN_train
  VAL_DIR: /content/MFDNet-main/GT-RAIN_train

  SAVE_DIR: "./checkpoints"

  SAVE_AFTER_EVERY: 10   # Save checkpoint every 10 epochs
